export declare const d2Hex: (s: string) => string;
export declare type CSSColorFormats = 'hex' | 'rgb' | 'hsl' | 'named';
export declare const checkFormat: (test: string, format: CSSColorFormats) => boolean;
export declare const convertPercentage: (percentage: number) => number;
export declare const parseSep: (str: string) => "," | " ";
export declare const hslData: (hsl: string) => number[];
export declare const rgbCalc: (h: number, s: number, l: number) => number[];
export declare const rgbData: (rgb: string) => string[];
export declare const hslCalc: (r: number, g: number, b: number) => number[];
